name: CBCPlugin
version: '2.0.0'
main: neonique.cbcplugin_new.CBCPlugin
depend: [CommandAPI]
api-version: '1.21'

permissions:
  cbcplugin.operator:
    default: false
    children:
      cbcplugin.host: true
  cbcplugin.host:
    default: false
